2023-01-17 14:40:11,167 -  nornir.core -     INFO -        run() - Running task 'print_stuff' with args {} on 6 hosts
2023-01-17 14:41:35,079 -  nornir.core -     INFO -        run() - Running task 'print_stuff' with args {} on 6 hosts
2023-01-17 14:42:45,588 -  nornir.core -     INFO -        run() - Running task 'print_stuff' with args {} on 6 hosts
2023-01-17 14:44:18,770 -  nornir.core -     INFO -        run() - Running task 'print_stuff' with args {} on 6 hosts
2023-01-17 14:44:27,485 -  nornir.core -     INFO -        run() - Running task 'print_stuff' with args {} on 6 hosts
2023-01-17 14:48:21,665 -  nornir.core -     INFO -        run() - Running task 'print_stuff' with args {} on 6 hosts
2023-01-17 14:48:29,484 -  nornir.core -     INFO -        run() - Running task 'print_stuff' with args {} on 6 hosts
2023-01-17 15:32:35,047 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 3 hosts
2023-01-17 15:39:10,464 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 2 hosts
2023-01-17 15:42:22,599 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'nortjhconfig.cfg'} on 2 hosts
2023-01-17 15:47:11,889 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconjfig.cfg'} on 2 hosts
2023-01-17 15:47:31,545 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconjfig.cfg'} on 2 hosts
2023-01-17 15:48:25,197 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'nolkjl'} on 2 hosts
2023-01-17 15:48:26,015 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 2055, in send_config_from_file
    with io.open(config_file, "rt", encoding="utf-8") as cfg_file:
FileNotFoundError: [Errno 2] No such file or directory: 'nolkjl'

2023-01-17 15:48:26,016 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'push_snmp' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/CodeSamples/Juniper-Automation/Nornir4-filtering/runbook2.py", line 16, in push_snmp
    task.run(task=netmiko_send_config, config_file=filename)
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_config (failed)


2023-01-17 15:48:26,019 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'netmiko_send_config' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 40, in netmiko_send_config
    result = net_connect.send_config_from_file(config_file=config_file, **kwargs)
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/netmiko/base_connection.py", line 2055, in send_config_from_file
    with io.open(config_file, "rt", encoding="utf-8") as cfg_file:
FileNotFoundError: [Errno 2] No such file or directory: 'nolkjl'

2023-01-17 15:48:26,020 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'push_snmp' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/CodeSamples/Juniper-Automation/Nornir4-filtering/runbook2.py", line 16, in push_snmp
    task.run(task=netmiko_send_config, config_file=filename)
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_config (failed)


2023-01-17 15:49:02,882 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 2 hosts
2023-01-17 15:49:43,816 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 2 hosts
2023-01-17 16:08:54,614 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 3 hosts
2023-01-17 16:15:14,818 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 2 hosts
2023-01-17 16:15:59,095 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 2 hosts
2023-01-17 16:16:58,577 -  nornir.core -     INFO -        run() - Running task 'push_snmp' with args {'filename': 'northconfig.cfg'} on 1 hosts
2023-01-17 17:03:28,093 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 3 hosts
2023-01-17 17:03:28,094 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: netmiko_send_command() missing 1 required positional argument: 'command_string'

2023-01-17 17:03:28,095 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: netmiko_send_command() missing 1 required positional argument: 'command_string'

2023-01-17 17:03:28,096 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: netmiko_send_command() missing 1 required positional argument: 'command_string'

2023-01-17 17:03:28,096 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'test_some_config' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/CodeSamples/Juniper-Automation/Nornir4-filtering/runbook4.py", line 11, in test_some_config
    task.run(
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_command (failed)


2023-01-17 17:03:28,096 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'test_some_config' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/CodeSamples/Juniper-Automation/Nornir4-filtering/runbook4.py", line 11, in test_some_config
    task.run(
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_command (failed)


2023-01-17 17:03:28,096 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'test_some_config' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/CodeSamples/Juniper-Automation/Nornir4-filtering/runbook4.py", line 11, in test_some_config
    task.run(
  File "/home/ipvzero/CodeSamples/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netmiko_send_command (failed)


2023-01-17 17:03:58,506 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 3 hosts
2023-01-17 17:05:54,055 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 2 hosts
2023-01-17 17:07:17,711 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 2 hosts
2023-01-17 17:08:31,551 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 4 hosts
2023-01-17 17:12:01,266 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 3 hosts
2023-01-17 17:14:00,770 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 6 hosts
2023-01-17 17:15:47,266 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 4 hosts
2023-01-17 18:00:05,162 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 3 hosts
2023-01-17 18:00:38,897 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 3 hosts
2023-01-17 18:04:14,930 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 2 hosts
2023-01-17 18:07:08,212 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 6 hosts
2023-01-17 18:07:58,893 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 4 hosts
2023-01-17 18:20:31,085 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 4 hosts
2023-01-17 18:21:35,451 -  nornir.core -     INFO -        run() - Running task 'test_some_config' with args {} on 3 hosts
